{% set name = "amundsen-rds" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amundsen-rds-{{ version }}.tar.gz
  sha256: a1a40cf584c73bbde2c7714c56de7721a530e31987e30ddc55ec277e671eefd2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - sqlalchemy >=1.3.0
    - alembic >=1.2,<2.0

test:
  imports:
    - amundsen_rds
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.github.com/amundsen-io/amundsenrds
  summary: Amundsen ORM Support
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - rxm7706
